#!/usr/bin/env python3
"""
Daily Lead Generation Script
Generates 10 leads and emails them to noctil.agent@agentmail.to
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Configuration
TARGET_EMAIL = "noctil.agent@agentmail.to"
LEADS_COUNT = 10
SEARCH_QUERY = "SaaS companies founded 2025"
LEADS_DB_PATH = Path.home() / ".openclaw" / "workspace" / "leads_database.json"

def load_leads_database():
    """Load the leads database to track sent leads"""
    if LEADS_DB_PATH.exists():
        with open(LEADS_DB_PATH, 'r') as f:
            return json.load(f)
    return {"sent_leads": [], "metadata": {"last_run": None, "total_sent": 0}}

def save_leads_database(db):
    """Save the leads database"""
    LEADS_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(LEADS_DB_PATH, 'w') as f:
        json.dump(db, f, indent=2)

def is_duplicate_lead(lead, db):
    """Check if lead was already sent"""
    company_website = lead.get('company', {}).get('website', '')
    contact_email = lead.get('contacts', [{}])[0].get('email', '')
    
    for sent_lead in db['sent_leads']:
        if (sent_lead.get('company_website') == company_website or
            sent_lead.get('contact_email') == contact_email):
            return True
    return False

def format_lead_email(lead):
    """Format a lead into email content"""
    company = lead.get('company', {})
    contact = lead.get('contacts', [{}])[0]
    
    subject = f"New Lead: {company.get('name', 'Unknown')} - {contact.get('title', 'Contact')}"
    
    body = f"""🎯 New Lead Discovery

Company: {company.get('name', 'N/A')}
Website: {company.get('website', 'N/A')}
Industry: {company.get('industry', 'N/A')}
Location: {company.get('location', 'N/A')}
Company Size: {company.get('size', 'N/A')}

---

Contact Information:
Name: {contact.get('name', 'N/A')}
Title: {contact.get('title', 'N/A')}
Email: {contact.get('email', 'N/A')}
LinkedIn: {contact.get('linkedin', 'N/A')}
Phone: {contact.get('phone', 'N/A')}

---

Company Summary:
{lead.get('company_summary', 'No summary available')}

Profile Summary:
{lead.get('profile_summary', 'No profile summary available')}

---

Source: {lead.get('source_url', 'N/A')}
Extracted: {lead.get('extracted_at', datetime.now().isoformat())}
Status: {lead.get('status', 'Complete')}

---
This lead was automatically generated by OpenClaw Lead-Gen-Pro
"""
    
    return subject, body

def send_lead_email(lead):
    """Send a lead via AgentMail"""
    subject, body = format_lead_email(lead)
    
    # Create email message
    email_data = {
        "to": TARGET_EMAIL,
        "subject": subject,
        "body": body,
        "timestamp": datetime.now().isoformat()
    }
    
    # Output for OpenClaw to process
    print(f"SEND_EMAIL: {json.dumps(email_data)}")
    
    return email_data

def generate_leads(count, search_query):
    """
    Generate leads using agent-browser and web search
    This is a placeholder - actual implementation would use agent-browser
    """
    print(f"Generating {count} leads for query: {search_query}")
    
    # Placeholder leads - in real implementation, this would:
    # 1. Use web search to find companies
    # 2. Use agent-browser to visit websites
    # 3. Extract contact information
    # 4. Generate summaries
    
    leads = []
    for i in range(count):
        lead = {
            "id": f"lead_{datetime.now().strftime('%Y%m%d')}_{i+1}",
            "company": {
                "name": f"Example Company {i+1}",
                "website": f"https://example{i+1}.com",
                "industry": "SaaS",
                "location": "London, UK",
                "size": "50-200"
            },
            "contacts": [
                {
                    "name": f"Contact Person {i+1}",
                    "title": "CEO",
                    "email": f"contact{i+1}@example{i+1}.com",
                    "linkedin": f"https://linkedin.com/in/contact{i+1}",
                    "phone": "+44-20-1234-5678"
                }
            ],
            "company_summary": f"Example Company {i+1} is a leading SaaS provider specializing in enterprise solutions.",
            "profile_summary": f"Contact Person {i+1} is an experienced executive with 10+ years in the industry.",
            "source_url": f"https://example{i+1}.com/about",
            "extracted_at": datetime.now().isoformat(),
            "status": "Complete"
        }
        leads.append(lead)
    
    return leads

def main():
    """Main execution function"""
    print(f"Starting daily lead generation at {datetime.now().isoformat()}")
    
    # Load leads database
    db = load_leads_database()
    
    # Generate leads
    leads = generate_leads(LEADS_COUNT, SEARCH_QUERY)
    
    # Filter out duplicates
    new_leads = [lead for lead in leads if not is_duplicate_lead(lead, db)]
    
    print(f"Generated {len(leads)} leads, {len(new_leads)} are new")
    
    # Send emails for new leads
    sent_count = 0
    failed_count = 0
    
    for lead in new_leads:
        try:
            email_data = send_lead_email(lead)
            
            # Track sent lead
            db['sent_leads'].append({
                "lead_id": lead['id'],
                "company_website": lead['company']['website'],
                "contact_email": lead['contacts'][0].get('email', ''),
                "sent_at": datetime.now().isoformat(),
                "email_status": "sent"
            })
            
            sent_count += 1
            
        except Exception as e:
            print(f"ERROR: Failed to send lead {lead['id']}: {e}", file=sys.stderr)
            failed_count += 1
    
    # Update metadata
    db['metadata']['last_run'] = datetime.now().isoformat()
    db['metadata']['total_sent'] = db['metadata'].get('total_sent', 0) + sent_count
    
    # Save database
    save_leads_database(db)
    
    # Print summary
    print(f"""
Daily Lead Generation Summary:
- Leads Generated: {len(leads)}
- New Leads: {len(new_leads)}
- Emails Sent: {sent_count}
- Failed: {failed_count}
- Total Leads Sent (All Time): {db['metadata']['total_sent']}
""")
    
    return 0 if failed_count == 0 else 1

if __name__ == "__main__":
    sys.exit(main())
